/**
 * Created by hqer on 16/12/7.
 */
import cookie from './cookies'
module.exports = {
    ajaxPath:{
        dev:"http://172.18.35.6:8415/mock/devPortal/",
        pro:cookie&&cookie.rootPath?cookie.rootPath:""
    },
    errorStatus:{
        "3001":"系统异常",
        "3002":"数据格式错误"
    },
    checkError:function(_r,_hashHistory){
        if(_r&&this.errorStatus[_r]){
            _hashHistory.push("/errorPage/"+_r+"?msg="+this.errorStatus[_r])
        }
    },
    headerState:{
        url:{
            dev:"headerState",
            pro:"/header/isLoginState.action"
        },
        type:"get",
        parms:{}
    },
    exitLogin:{
        url:{
            dev:"exitLogin",
            pro:"/header/exitLogin.action"
        },
        type:"get",
        parms:{}
    },
    //我的工作台基本信息
    myServerInfo:{
        url:{
            dev:"myServerInfo",
            pro:"/myCenter/getApiUserInfo.action"
        },
        type:"post",
        parms:{}
    },
    //我的工作台统计信息
    myServerCount:{
        url:{
            dev:"myServerCount",
            pro:"/myCenter/getApiInvokeTimesByUser.action"
        },
        type:"post",
        parms:{}
    },
    //我的工作台能力管理列表数据
    myServerAbility:{
        url:{
            dev:"myServerAbility",
            pro:"/myCenter/getApiListByUser.action"
        },
        type:"post",
        parms:{}
    },
    /*开通立即使用、立即试用、正式开通等能力接口*/
    openAbility:{
        url:{
            dev:"openAbility",
            pro:"/orderOperating/iSExitPreApi.action"
        },
        type:"post",
        parms:{
            eaId:"",
            token:""
        }
    },
    /*获取我的应用列表信息*/
    myApps:{
        url:{
            dev:"myApp",
            pro:"/app/getAppInfoList.action"
        },
        type:"post",
        parms:{
            pageNow:"",
            pageSize:"",
            status:""
        }
    },
    /*重置SecretKey*/
    reSecretKey:{
        url:{
            dev:"reSecretKey",
            pro:"/app/resetAppKey.action"
        },
        type:"post",
        parms:{
            appId:"",
            token:""
        }
    },
    /*删除我的应用*/
    delMyApps:{
        url:{
            dev:"delMyApps",
            pro:"/app/deleteApp.action"
        },
        type:"post",
        parms:{
            delId:[],
            token:""
        }
    },
    /*撤回我的应用*/
    cancelMyApps:{
        url:{
            dev:"cancelMyApps",
            pro:"/app/cancleMyApps.action"
        },
        type:"post",
        parms:{
            cancelId:"",
            token:""
        }
    },
    /*提交我的应用*/
    submitMyApps:{
        url:{
            dev:"submitMyApps",
            pro:"/app/submitMyApps.action"
        },
        type:"post",
        parms:{
            submitId:"",
            token:""
        }
    },
    /*新增或修改我的应用*/
    addMyApp:{
        url:{
            dev:"addMyApp",
            pro:"/app/createApp.action"
        },
        type:"post",
        parms:{
            appId:"",
            name:"",
            category:"",
            des:"",
            token:""
        }
    },
    /*校验应用名称是否重复*/
    checkAppName:{
        url:{
            dev:"checkAppName",
            pro:"/app/isAppNameUnique.action"
        },
        type:"post",
        parms:{
            appId:"",
            appName:""
        }
    },
    /*我的应用详情*/
    myAppDetail:{
        url:{
            dev:"myAppDetail",
            pro:"/app/getAppInfoDetail.action"
        },
        type:"post",
        parms:{
            appId:""
        }
    },
    /*根据查询条件获取语音模板列表*/
    searchVoiceTemplate:{
        url:{
            dev:"searchVoiceTemplate",
            pro:""
        },
        type:"post",
        parms:{
            searchItem:0,
            searchItem1:"",
            status:-1,
            pageNow:1,
            token:""
        }
    },
    /*删除语音模板*/
    delVoiceTemplate:{
        url:{
            dev:"delVoiceTemplate",
            pro:""
        },
        type:"post",
        parms:{
            delId:[],
            token:""
        }
    },
    /*获取语音模板详情*/
    voiceTemplateDetail:{
        url:{
            dev:"voiceTemplateDetail",
            pro:""
        },
        type:"post",
        parms:{
            voiceId:"",
            token:""
        }
    },
    /*校验短信模板名称是否重复*/
    checkVoiceTemplateName:{
        url:{
            dev:"checkVoiceTemplateName",
            pro:""
        },
        type:"post",
        parms:{
            name:""
        }
    },
    /*新增或修改语音模板*/
    addVoiceTemplate:{
        url:{
            dev:"addVoiceTemplate",
            pro:""
        },
        type:"post",
        parms:{
            name:"",
            content:"",
            token:""
        }
    },
    /*根据查询条件获取订单列表*/
    searchOrderManage:{
        url:{
            dev:"searchOrderManage",
            pro:"/orderManager/getOrderManageList.action"
        },
        type:"post",
        parms:{
            orderId:"",
            orderName:"",
            status:"",
            time0:"",
            time1:""
        }
    },
    /*删除订单*/
    delOrderItem:{
        url:{
            dev:"delOrderItem",
            pro:"/orderManager/deleteOrderItem.action"
        },
        type:"post",
        parms:{
            orderId:"",
            token:""
        }
    },
    /*关闭订单*/
    closeOrderItem:{
        url:{
            dev:"closeOrderItem",
            pro:"/orderManager/backOrderItem.action"
        },
        type:"post",
        parms:{
            orderId:"",
            token:""
        }
    },
    /*确认关闭订单*/
    verifyCloseOrderItem:{
        url:{
            dev:"verifyCloseOrderItem",
            pro:"/orderManager/unsubscribe.action"
        },
        type:"post",
        parms:{
            orderId:"",
            token:""
        }
    },
    /*订单详情页*/
    orderItemDetail:{
        url:{
            dev:"orderItemDetail",
            pro:"/orderManager/getOrderDetail.action"
        },
        type:"post",
        parms:{
            orderId:""
        }
    },
    /*查询选择订单下的应用列表*/
    getOrderAppList:{
        url:{
            dev:"getOrderAppList",
            pro:"/orderOperating/getNotOrderedApp.action"
        },
        type:"post",
        parms:{
            eaId:""
        }
    },
    /*各能力API产品配置信息(type:0输入框，1下拉列表，2复选框，3文本域，4上传插件)*/
    abilityAPIData:{
        url:{
            dev:"abilityAPIData",
            pro:"/orderOperating/getOrderConfigInfo.action"
        },
        type:"post",
        parms:{
            eaId:"",
            orderId:""
        }
    },
    /*获取账户管理页信息*/
    getOrderPackage:{
        url:{
            dev:"getOrderPackage",
            pro:"/orderOperating/getApiChargeStrategy.action"
        },
        type:"post",
        parms:{
            eaId:""
        }
    },
    /*提交套餐*/
    postOrder:{
        url:{
            dev:"postOrder",
            pro:"/orderOperating/createOrder.action"
        },
        type:"post",
        parms:{
            eaId:"",
            appId:"",
            typeId:"",
            token:""
        }
    },
    /*获取单个套餐详情信息*/
    getOrderPackItem:{
        url:{
            dev:"getOrderPackItem",
            pro:"/orderOperating/getApiAndChargeInfo.action"
        },
        type:"post",
        parms:{
            eaId:"",
            typeId:""
        }
    },
    /*获取单个套餐详情信息*/
    getRestAPI:{
        url:{
            dev:"getRestAPI",
            pro:"/restApi/restApi.action"
        },
        type:"post",
        parms:{}
    },
    getAjaxParms:function(_action){
        var _e = window.GLOBAL._environment;
        var _a = this[_action];
        var _ajaxPath = this["ajaxPath"][_e];
        if(_a){
            return {url:_ajaxPath+_a.url[_e],type:_a.type,data:_a.parms};
        }
        return {};
    },
    setParm:function(_action,_parm,_v){
        if(typeof _v !== "undefined"){
            this[_action].parms[_parm] = _v;
        }
    },
    setParms:function(_action,_parms){
        if(typeof _parms === "object"){
            this[_action].parms = _parms;
        }
    }
}
