/**
 * Created by hqer on 16/12/7.
 */
module.exports = {
    footer:{
        gsjj:{
            text:"公司简介",
            url:"/About"
        },
        lxwm:{
            text:"联系我们",
            url:"/About"
        },
        ghs:{
            text:"浙公网安备33011002010472号",
            url:"/ghs",
            img:"img/ghs.png"
        },
        txbq:{
            text:"杭研开平签[2015]4号 中国移动通信版权所有"
        }
    },
    header:{
        logo:{
            text:"贯众开放平台"
        },
        devDoc:{
            text:"开发者文档",
            child:[
                {text:"开发者指南",key:"companion",url:"/companion"},
                {text:"REST API",key:"restAPI",url:"/restAPI?d="+encodeURIComponent("html/00001.html")},
                {text:"服务协议",key:"agreement",url:"/agreement"},
                {text:"常见问题",key:"FQA",url:"/FQA"}
            ]
        },
        ability:{
            text:"能力服务",
            child:[
                {
                    text:"音视频类",
                    child:[
                        {text:"多方通话",key:"voiceItem0",url:"/introduction/00001"},
                        {text:"呼叫控制",key:"voiceItem1",url:"/introduction/00001"},
                        {text:"IVR",key:"voiceItem2",url:"/introduction/00001"},
                        {text:"外呼",key:"voiceItem3",url:"/introduction/00001"},
                        {text:"号码改变",key:"voiceItem4",url:"/introduction/00001"}
                    ]
                },
                {
                    text:"消息类",
                    child:[
                        {text:"短消息",key:"smsItem0",url:"/introduction/00001"},
                        {text:"多媒体消息",key:"smsItem1",url:"/introduction/00001"},
                        {text:"USSD",key:"smsItem2",url:"/introduction/00001"}
                    ]
                },
                {
                    text:"管道类",
                    child:[
                        {text:"QOS",key:"passageItem0",url:"/introduction/00001"}
                    ]
                }
            ]
        },
        myServer:{
            text:"我的工作台",
            url:"/myServer"
        },
        exitUrl:"/",
        unLoginBtns:[
            {
                text:"注册",
                key:"registration",
                url:""
            },
            {
                text:"登录",
                key:"login",
                url:""
            }
        ]
    },
    devDoc:{
        leftMenu:[
            {
                text:"开发者指南",
                child:[
                    {key:"companion", text:"平台介绍", url:"/companion"}
                ],
                icon:1
            },
            {
                text:"REST API",
                //child:[
                //    {key:"restAPI", text:"呼叫状态通知", url:"/restAPI"}
                //],
                key:"restAPI",
                icon:2,
                url:"/restAPI"
            },
            {
                text:"服务协议",
                child:[
                    {key:"agreement", text:"平台服务协议", url:"/agreement"}
                ],
                icon:4
            },
            {
                text:"常见问题",
                url:"/FQA",
                key:"FQA",
                icon:5
            }
        ]
    },
    introduction:{
        "00001":{
            title:"消息",
            text:"语音通知是指被叫一方是落地的手机或固话，另一方是服务器，或者互联网设备、软件或手机客户端，如手机App、Web、PC 客户端、软终端等。单向IVR语音播报是典型场景。",
            img:"img/manyvov.png",
            bannerColor:"#ccede6",
            titleColor:"#4ecb9f",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"多媒体消息",
                        text:"支持发送、接收及多媒体消息状态查询，并可通过状态报告确认消息是否送达",
                        icon:"icon-de4f"
                    },
                    {
                        title:"短消息",
                        text:"支持发送、接收及文本消息状态查询，并可通过状态报告确认消息是否送达",
                        icon:""
                    },
                    {
                        title:"USSD",
                        text:"开放向用户下发USSD消息能力，并支持对发送消息状态的查询和状态上报",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"能力套餐价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/条)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"物流通知",
                        text:"当物流状态发生变化时，系统自动下发发货通知、收货提醒等。",
                        icon:"icon-car",
                        bgColor:"#e0fcef"
                    },
                    {
                        title:"付款回执",
                        text:"金融账户发生交易行为时，实时向用户通知账户金额变更。",
                        icon:"icon-bankC",
                        bgColor:"#d6f8fa"
                    }
                ]
            }
        },
        "00002":{
            title:"外呼",
            text:"语音通知是指被叫一方是落地的手机或固话，另一方是服务器，或者互联网设备、软件或手机客户端，如手机App、Web、PC 客户端、软终端等。单向IVR语音播报是典型场景。",
            img:"img/manyvov.png",
            bannerColor:"#ccede6",
            titleColor:"#4ecb9f",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"外呼一方",
                        text:"应用发起到指定用户号码的呼叫，与被叫建立通话",
                        icon:""
                    },
                    {
                        title:"外呼两方",
                        text:"应用分别发起向主叫、被叫的呼叫，主被叫建立通话",
                        icon:""
                    },
                    {
                        title:"多方通话",
                        text:"包括发起和结束语音多方通话，多方语音通话控制，多方语音通话事件上报等能力",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"能力套餐价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/分钟)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"客服通话",
                        text:"在PC端向用户发起语音通话，操作便捷。",
                        icon:"",
                        bgColor:"#e0fcef"
                    },
                    {
                        title:"社交软件",
                        text:"在软件内内置双向语音，丰富功能的同时保障网络社交的安全性。",
                        icon:"",
                        bgColor:"#e0fcef"
                    }
                ]
            }
        },
        "00003":{
            title:"消息",
            text:"语音通知是指被叫一方是落地的手机或固话，另一方是服务器，或者互联网设备、软件或手机客户端，如手机App、Web、PC 客户端、软终端等。单向IVR语音播报是典型场景。",
            img:"",
            bannerColor:"#ccede6",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"发起、结束通话",
                        text:"发起、结束多个号码邀请进一个语音多方通话并结束",
                        icon:""
                    },
                    {
                        title:"增加、删除参与方",
                        text:"将指定的一个已加入的用户踢出多方通话或者邀请指定用户加入",
                        icon:""
                    },
                    {
                        title:"多方通话事件通知",
                        text:"获取多方通话召开，多方通话结束，用户离开多方通话等事件",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"能力套餐价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/分钟)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"物流通知",
                        text:"当物流状态发生变化时，系统自动下发发货通知、收货提醒等。",
                        icon:""
                    },
                    {
                        title:"订单通知",
                        text:"O2O平台有用户下单时，通过拨打商家电话进行语音通知，可提高接单速度。",
                        icon:""
                    }
                ]
            }
        },
        "00004":{
            title:"QoS能力",
            text:"流量的QOS控制，可向应用开放针对2/3/4G下的用户QOS(包括APN-AMBR，QCI，ARP，MBR/GBR)进行控制。",
            img:"",
            bannerColor:"#ccede6",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"QoS资源申请、释放",
                        text:"企业用户通过上网助手，可面向特定用户群体，在用户通过手机浏览器上网时向用户推送经系统审核过的信息",
                        icon:""
                    },
                    {
                        title:"QoS资源修改",
                        text:"为企业提供用户手机访问企业域名时的带宽保障，从而达到网络提速的效果",
                        icon:""
                    },
                    {
                        title:"QoS状态事件报告",
                        text:"支持家庭光纤宽带用户提速",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"能力套餐价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/次)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"手机上网安全保障",
                        text:"在用户通过手机浏览器上网时，向用户推送经系统审核过的信息",
                        icon:""
                    },
                    {
                        title:"宽带提速",
                        text:"支持家庭光纤宽带用户提速",
                        icon:""
                    }
                ]
            }
        },
        "00005":{
            title:"呼叫控制",
            text:"对网络的呼叫控制处理固定逻辑进行封装，面向应用开放基于Restful的API，提供对用户的呼叫控制能力。",
            img:"",
            bannerColor:"#ccede6",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"呼叫事件订阅",
                        text:"可订阅的呼叫事件包括：呼叫开始、振铃、用户应答、忙、不可达、无应答、用户挂机等",
                        icon:""
                    },
                    {
                        title:"呼叫事件通知",
                        text:"将用户的呼叫事件推送给应用，应用可以根据用户呼叫时间进行开发",
                        icon:""
                    },
                    {
                        title:"呼叫接续控制",
                        text:"根据应用指示控制能力平台进行呼叫接续控制，包括接续呼叫和释放呼叫",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"API价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/次)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"用户分析",
                        text:"对用户的呼叫事件数据进行分析，有针对性的提供特色服务。",
                        icon:""
                    },
                    {
                        title:"电话拦截",
                        text:"对用户的来电号码进行判断，若属于黑名单则挂断拦截。",
                        icon:""
                    }
                ]
            }
        },
        "00006":{
            title:"号码改变",
            text:"对用户号码进行加工，发起呼叫时添加前缀或更改为其它号码。",
            img:"",
            bannerColor:"#ccede6",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"号码添加前缀",
                        text:"用户发起呼叫时，根据应用指示，在被叫号码前添加指定的前缀",
                        icon:""
                    },
                    {
                        title:"号码翻译API",
                        text:"用户发起呼叫时，根据应用指示，修改主、被叫号码为绑定的新号码",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"API价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/次)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"客服电话",
                        text:"向原有号码添加前缀，提高客服电话号码辨识度。",
                        icon:""
                    },
                    {
                        title:"保护隐私",
                        text:"呼叫时隐藏用户真实号码，对原有号码进行隐私保护。",
                        icon:""
                    }
                ]
            }
        },
        "00007":{
            title:"IVR能力",
            text:"通过调用IVR API实现在网络用户通话中的放音收号功能的调用，在IVR API中携带放音收号文件URL，网络根据放音收号文件URL获取对应文件进行放音收号处理。",
            img:"",
            bannerColor:"#ccede6",
            item0:{
                title:"功能简介",
                child:[
                    {
                        title:"下发IVR",
                        text:"根据指示中的URL获取放音收号文件，并解析文件，播放给指定号码用户",
                        icon:""
                    },
                    {
                        title:"上报IVR",
                        text:"收集用户的收号或录音指示处理结果，上报给应用",
                        icon:""
                    }
                ]
            },
            item1:{
                title:"API价格",
                eaIdList:[],
                listTitle:["API产品",'计费类型','计费数量','价格(元/次)'],
                showKey:['name','norms','num','price']
            },
            item2:{
                title:"使用场景",
                child:[
                    {
                        title:"物流通知",
                        text:"当物流状态发生变化时，系统自动下发发货通知、收货提醒等。",
                        icon:""
                    },
                    {
                        title:"订单通知",
                        text:"O2O平台有用户下单时，通过拨打商家电话进行语音通知，可提高接单速度。",
                        icon:""
                    },
                    {
                        title:"紧急通知",
                        text:"有重要或紧急的消息需要通知时，使用语音可让用户接收更及时。",
                        icon:""
                    },
                    {
                        title:"批量语音通知",
                        text:"当需要向大量用户发送相似内容时，可一次性向多个用户发起语音通知。",
                        icon:""
                    }
                ]
            }
        }
    },
    leftMenu:{
        item0: {
            text:"API管理",
            child:[
                {key:"myServer", text:"我的API", url:"/myServer"},
                {key:"myApps", text:"我的应用", url:"/myApps"},
                {key:"voiceTemplate", text:"语音模板", url:"/voiceTemplate",ischeck:true}
            ]
        },
        item2:{
            text:"订单管理",
            child:[
                {key:"orderManage", text:"订单管理", url:"/orderManage"}
            ]
        },
        item3:{
            text:"用户中心",
            child:[
                {key:"accountManage", text:"账号信息", url:""},
                {key:"changePWD", text:"密码更改", url:""},
                {key:"certification", text:"认证信息", url:""},
                {key:"message", text:"站内消息", url:"",isShow:true}
            ]
        }
    },
    checkTips:{
        img:"img/tm.png",
        phone:{
            maxLength:11,
            placeholder:"请输入真实的手机号码"
        },
        imgCode:{
            maxLength:4,
            placeholder:"请输入图形验证码"
        },
        smsCode:{
            maxLength:6,
            placeholder:"请输入您获取到的验证码"
        }
    },
    orderNew:{
        listTitle:["",'计费类型','计费方式','计费数量','价格'],
        showKey:['typeId','norms','ways','num','price'],
        numInput:{
            maxLength:3,
            maxValue:999
        },
        tips:{className:"center",text:"请选择套餐!",btns:[{text:"确定",type:0}]},
        uploadMp3:{
            baseUrl:"",
            accept:"audio/mpeg",
            maxSize:2*1048576,
            domeUrl:""
        }
    },
    orderToPay:{
        listTitle:['API产品名称','计费类型','计费方式','计费数量','价格'],
        showKey:['name','norms','ways','num','price'],
        tips:{className:"center",text:"请选择支付方式!",btns:[{text:"确定",type:0}]}
    },
    myServer:{
        title:"我的API产品",
        img:"img/user.gif",
        logoType:[
            "",
            "icon-user_flow icon",
            "icon-user_message icon",
            "icon-user_money icon",
            "icon-user_call icon"
        ],
        iconText:[
            "",
            "未订购",
            "已订购",
            "冻结"
        ],
        level:[
            "音视频类API产品",
            "消息能力",
            "智能管道能力"
        ],
        Unautherized:{
            className:"left",
            text:"您还未完成开发者身份认证,认证后方可订购收费能力,是否进行认证审核?",
            btns:[{text:"去认证",type:1},{text:"取消",type:0}]
        },
        firstLogin:{
            className:"left",
            title:"欢迎登录贯众开放平台!",
            text:"平台用户信息认证审核通过后,方可正式开通能力,是否立即开始认证?",
            btns:[{text:"去认证",type:1},{text:"取消",type:0}]
        },
        unOrder:{
            className:"left",
            text:"请先购买呼叫事件通知API,和呼叫连接控制API产品!",
            btns:[{text:"确定",type:0}]
        },
        freeze:{
            className:"center",
            text:"您的账户已被冻结,暂无法使用!",
            btns:[{text:"确定",type:0}]
        }
    },
    myApps:{
        title:"我的应用",
        listTitle:['应用名称','状态','创建时间','调用参数','操作'],
        showKey:['title','status','date','parms','btns'],
        hid:"································································································",
        reSecretKey:{className:"center",text:"点击重置按钮后,Secret Key会重新生成."},
        del:{className:"left",text:"您的删除申请已经提交，请耐心等待管理员审核。"},
        del1:{className:"center",text:"您正在进行应用删除操作，请确认是否删除？"},
        detailTitle:"应用详情",
        myAppsModify:{
            title:"修改应用",
            name:{
                maxLength:15
            },
            text:{
                maxLength:256
            }
        },
        category:[{text:"OAuth2.0",value:2},{text:"HTTP basic",value:1}],
        status:[{text:"审核通过",value:1},{text:"冻结",value:2},{text:"注销",value:3},{text:"删除",value:4},{text:"待提交",value:5},{text:"审核中",value:6},{text:"审核不通过",value:7},{text:"删除中",value:8}],
        myAppsAdd:{
            title:"创建应用",
            name:{
                maxLength:15
            },
            text:{
                maxLength:256
            }
        }
    },
    voiceTemplate:{
        title:"语音模板配置",
        listTitle:['delAllCheck','模板名称','模板ID','状态','最近更新时间','操作'],
        showKey:['delCheck','name','appId','status','time','btns'],
        delTemplate:{className:"center",text:"确认删除该模板?"},
        cancelTemplate:{className:"center",text:"该模板正在等待管理员审核,确认撤回吗?"},
        searchItem:[{text:"模板名称",value:0},{text:"模板ID",value:1}],
        status:[{text:"待提交",value:0},{text:"审核中",value:1},{text:"审核通过",value:2},{text:"审核不通过",value:3}],
        voiceTemplateDetail:{
            title:"语音模板详情"
        },
        voiceTemplateAdd:{
            title:"新建语音模板",
            name:{
                maxLength:15
            },
            content:{
                maxLength:200,
                parms:10,
                underTips:"* 请按照示例编写模板内容,模板参数用'{}'分隔标注,单条语音通知模板最多200个字符,最多包含10个参数.<br/>示例:尊敬的{param1}用户,您的验证码为{param2},本验证码{param3}分钟有效,感谢您的使用!"
            },
            parmsType:[{text:"string",value:"string"},{text:"number",value:"number"},{text:"datetime",value:"datetime"},{text:"url",value:"url"},{text:"int",value:"int"}],
            parmsLength:{
                maxLength:3,
                maxValue:100
            },
            parmsDes:{
                maxLength:150
            },
            scene:{
                maxLength:300
            },
            tips:[
                {className:"left",text:"参数个数必须和模板内容中参数个数保持一致.",btns:[{text:"确定",type:0}]},
                {className:"left",text:"您已提交单向语音模板,管理员正在审核中,请耐心等待!",btns:[{text:"确定",type:1}]}
            ]
        },
        smsTemplateModify:{
            title:"修改语音模板"
        }
    },
    orderManage:{
        title:"订单管理",
        status:[{text:"有效",value:1},{text:"审核中",value:4},{text:"即将失效",value:6},{text:"失效",value:2},{text:"冻结",value:7},{text:"审核不通过",value:5},{text:"退订中",value:3},{text:"待生效",value:9}],
        listTitle:['API名称','计费类型','计费方式','计费数量','价格','所属应用','操作'],
        showKey:['name','norms','ways','num','price','ability','btns'],
        delOrderItem:{className:"center",text:"确认该订单从列表中删除吗?"},
        closeOrderItem:{className:"left",text:"点击退订后，将不能继续使用该产品,请确认是否退订?"},
        closeOrderItem1:{className:"left",text:"确认退订后，订单失效，退订成功。确认执行该操作吗?"},
        orderItemDetail:{
            title:"订单详情",
            listTitle:['API名称','计费类型','计费方式','计费数量','价格'],
            showKey:['name','norms','ways','num','price']
        }
    },
    dateRangePickerLocale:{
        format: 'YYYY-MM-DD',
        separator: " - ",
        applyLabel: "确定",
        cancelLabel: "取消",
        fromLabel: "起始时间",
        toLabel: "结束时间'",
        customRangeLabel: "自定义",
        weekLabel: "W",
        daysOfWeek: ["日", "一", "二", "三", "四", "五", "六"],
        monthNames: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
        firstDay: 1
    },
    highchartsConfig:{
        credits:{
            enabled:false
        },
        title: {
            text: '',
            x: -20
        },
        subtitle: {
            text: '',
            x: -20
        },
        xAxis: {
            tickmarkPlacement:'on',
            lineColor: '#cccccc',
            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
            labels: {
                step:1,
                rotation:0
            }
        },
        yAxis: {
            lineWidth: 0,
            title: {
                text:""
            },
            min: 0
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            borderWidth: 0
        },
        series: [{
            data: [29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 295.6, 454.4]
        }],
        colors: ['#ffac62', '#4ecb9f', '#90ed7d', '#f7a35c', '#8085e9',
            '#f15c80', '#e4d354', '#2b908f', '#f45b5b', '#91e8e1']
    },
    FileUploadOptions:{}
};